### ISSUE TITLE
Y7000P选择安装，苹果Logo一闪一过之后，风扇开始疯狂的转，过会关机。

### ISSUE THREAD

**Issue by mustkass** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh_Clover#29]
一开始以为是三星硬盘的问题，便在空留的机械硬盘位置上安装了西数STAT的固态硬盘，按照视频开始分区，问题一样，之后拆除三星硬盘，也是如此。

EFI里面已添加了屏蔽三星硬盘的文件。

配置如下：联想Y7000P 20119款
处理器：I7-9750H
内存：16GB
显卡：GTX1600Ti
硬盘：IT三星固态，500G西数固态

请问，如何做可以解决？

**Comment by xiaoMGitHub** [comment]
@mustkass 关闭显卡直连即可

**Comment by mustkass** [comment]
好的，已解决，感谢
