### ISSUE TITLE
联想Y70002019款温度无法显示，风扇不转

### ISSUE THREAD

**Issue by Stonewalling** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh_Clover#30]
联想Y70002019款温度无法显示，风扇不转，硬盘部位温度偏高

**Comment by xiaoMGitHub** [comment]
@Stonewalling 不显示温度可以自行添加传感器驱动，风扇是转的只是温度未达到，nvme温度高可以更好intel 760P
