### ISSUE TITLE
请问, 你有没有碰上睡眠唤醒后,内置摄像头没了的情况?

### ISSUE THREAD

**Issue by alexlipe** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh_Clover#33]
睡眠唤醒后, 摄像头没了. 用IO看了一下. 原摄像头设备被删除, 唤醒后出现一个新的设备.

**Comment by xiaoMGitHub** [comment]
@alexlipe 有动过我的EFI？

**Comment by alexlipe** [comment]
我都有点混乱了, 因为同时参考了好几个人的efi. 没有用你的usbx

**Comment by xiaoMGitHub** [comment]
@alexlipe 你直接整个替换我的EFI，然后执行命令，可以解决很多问题

**Comment by alexlipe** [comment]
好的,谢谢. 晚上回去我试试
