### ISSUE TITLE
Wake + Sleep 

### ISSUE THREAD

**Issue by Malvik298** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh_Clover#34]
How you got the wake and Sleep working ?

**Comment by xiaoMGitHub** [comment]
Remove USB related patches and drivers, add SSDT-GPRW.aml, SSDT-PTSWAK.aml

**Comment by Malvik298** [comment]
I tried PTSWAK.aml didn't removed the USB patches.
 , I got the screen turning on but it works for only 3 times

**Comment by Malvik298** [comment]
And BTW the BIOS issue got solved. I'll confirm for it perfect working and thank you for all the work that you have done for legion series. I really appreciate it.

**Comment by xiaoMGitHub** [comment]
Unfortunately, the current 10.15 is very unfriendly to y530 support.

**Comment by RaviKavaiya** [comment]
@xiaoMGitHub what are the problems in Y530 for 10.15 catalina??
I have Legion Y530, with i5-8300H. Should I install Mojave first and then update to Catalina or directly install Catalina?

**Comment by xiaoMGitHub** [comment]
@RaviKavaiya I think it is hardware incompatible, even if it is installed, it is very unstable.I suggest you stay at 10.13.6-10.14.6.

**Comment by Malvik298** [comment]
I am currently using High Sierra 10.13.6
