### ISSUE TITLE
Which EFI folder to use

### ISSUE THREAD

**Issue by RaviKavaiya** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh_Clover#35]
Hello @xiaoMGitHub , I want to install Mojave on my Y530.
So, which EFI folder should I use?
1) Clone your GitHub repository
2) 2.0.3 release

There are many commits after 2.0.3 release. What is the difference?

**Comment by xiaoMGitHub** [comment]
@RaviKavaiya You can only use the EFI of the release page. The GitHub repository is just a backup of my EFI part files.

**Comment by RaviKavaiya** [comment]
@xiaoMGitHub  One more thing, why the 2.0.3 release contains only 32-bit drivers??
Older releases had 64-bit drivers (drivers64UEFI)

**Comment by xiaoMGitHub** [comment]
@RaviKavaiya The file structure of clover has changed.
