### ISSUE TITLE
三星970evo 是否可以安装黑果

### ISSUE THREAD

**Issue by HXChow** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh_Clover#37]
如题
刚刚换了固态 三星970evo 512G
电脑是y7000 2018
i5 8300H 1050ti 16G 512G固态+1t机械

还有博通网卡我看淘宝上好多种价位的和不同接口的（y7000的网卡接口是什么样的？） 不知道选哪一个好，望请赐教

**Comment by xiaoMGitHub** [comment]
970evo  plus不能装，970evo 应该是没问题
