### ISSUE TITLE
ALCPlugFix sleep issue

### ISSUE THREAD

**Issue by inabhi9** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh_Clover#40]
Can you check and include ALCPlugFix from https://github.com/Sniki/ALCPlugFix repo

Current version in your repo doesn't have hook for wake or doesn't work in Catalina after wake. Meaning if headphone is already plugged during sleep, ALCPlugFix doesn't run hda-verb after wake-up and have to re-plug a headphone.

I've compiled myself and it works well.

**Comment by xiaoMGitHub** [comment]
I have been using ALCPlugFix, but it is included in my [script](https://gitee.com/xiaoMGit/Y7000Series_Hackintosh_Fix/blob/master/Script/Optimize.sh#L55).

**Comment by inabhi9** [comment]
I also have been using but it does not fix audio after wake up if headphone is already plugged in.
Try this to reproduce
- Plug in the headphone
- Sleep the laptop (keep headphone plugged-in)
- Wake up your system and try to listen something, you'll hear crackling sound

**Comment by xiaoMGitHub** [comment]
It seems that this problem really exists. How did you solve it? Can you talk in detail?

**Comment by inabhi9** [comment]
It seems MacOS resets codec upon wakeup and the ALCPlugFix has to set codec again using hda-verb upon wakeup. It seems your version of ALCPlugFix doesn't run hda-verb upon wake up.

The repository I mentioned in the first post solved that issue. We just need to modify it for our codec version.

I already compiled it for our laptop model if you don't want to take hurdle to compile it again. here is the file: [ALCPlugFix.zip](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh_Clover/files/3855208/ALCPlugFix.zip)

**Comment by xiaoMGitHub** [comment]
Do you know what SET_UNSOLICITED_ENABLE does?After I modified these two [lines](https://github.com/Sniki/ALCPlugFix/blob/master/ALCPlugFix/main.m#L136), everything is fine.I modified them to be like this.
```
NSString *output1 = [[binPrefix stringByAppendingString:@"hda-verb 0x12 SET_PIN_WIDGET_CONTROL 0x20"] runAsCommand];  
NSString *output2 = [[binPrefix stringByAppendingString:@"hda-verb 0x19 SET_PIN_WIDGET_CONTROL 0x24"] runAsCommand];
```

**Comment by inabhi9** [comment]
I don't know either but I've made the changes same as you did. And it's
working fine so far

**Comment by inabhi9** [comment]
I think we don't need hda-verb at all. Can you try installation instruction mentioned in AppleALC repo? i.e.
- Disable renaming HDAS to HDEF
- Adding HDEF property to device list

**Comment by xiaoMGitHub** [comment]
I think this is a defect of AppleALC, because my other laptop does not need to use ALCPlugFix everything is normal.

**Comment by inabhi9** [comment]
Strange! I tried removing ALCPlugFix and modified `config.plist` as described and it worked without any issue.

**Comment by xiaoMGitHub** [comment]
After you removed ALCPlugFix, everything works fine? Are you sure you completely deleted ALCPlugFix and rebooted?

**Comment by inabhi9** [comment]
Yes everything works fine. I'm 100% sure I removed everything related to ALCPlugFix (daemon and launch agent) and also made sure daemon is not running at all

**Comment by xiaoMGitHub** [comment]
I seem to ignore a point, you are y540, your sound card model is different from mine. My model is ALC236 and it seems that I have to use ALCPlugFix to be normal.
