### ISSUE TITLE
Y740

### ISSUE THREAD

**Issue by august0xf** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh_Clover#41]
Hi,can you add support for y740?
I was able installing catalina using niresh,but uhd 630 doesnt work for me.

Thanks

**Comment by xiaoMGitHub** [comment]
Theoretically, [2.0.3](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh_Clover/releases/tag/v2.0.3) supports Y740, but it may not be perfect.It is recommended that you use 2.0.3.

**Comment by august0xf** [comment]
> Theoretically, [2.0.3](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh_Clover/releases/tag/v2.0.3) supports Y740, but it may not be perfect.It is recommended that you use 2.0.3.

after many fail , and yes today iam succed install Mojave 10.14.6 vanilla with injected uhd630
but for now sound and touchpad not working

do you recommend setting for sound? I don't know table layout what should I use

**Comment by xiaoMGitHub** [comment]
@august0xf This problem should be caused by the difference between the sound card models of y740 and y530. You need to find your sound card model and then inject the correct id. The sound card id can be found [here](https://github.com/acidanthera/AppleALC/wiki/Supported-codecs).

**Comment by august0xf** [comment]
> @august0xf This problem should be caused by the difference between the sound card models of y740 and y530. You need to find your sound card model and then inject the correct id. The sound card id can be found [here](https://github.com/acidanthera/AppleALC/wiki/Supported-codecs).

Okay thank you,ill try To find out 👍🏼
