### ISSUE TITLE
HDMI 有解决方案吗？

### ISSUE THREAD

**Issue by gclm** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh_Clover#42]
可以支持其他HDMI 方案吗？

- DP -> HDMI
- 其他转 HDMI

**Comment by xiaoMGitHub** [comment]
USB转HDMI

**Comment by gclm** [comment]
那是否需要打补丁呢？只要是普通的 USB -> HDMI 就可以了是吧，还是说需要特定型号的呢？

**Comment by xiaoMGitHub** [comment]
京东搜索USB转HDMI，低于150的直接忽视，建议250以上，价格越贵输出质量越好，找到合适的问客服是否支持mac，顺便问客服要驱动

**Comment by gclm** [comment]
现在看了之后发现高于 150 的大部分都是 type -c 版的啊，但是官方客服说 type-c 连接的是独显啊。不知道是否有具体型号推荐呢？  我连接方式 QQ：1719982754

**Comment by xiaoMGitHub** [comment]
绿联有一款256的USB转hdmi，好几个群友都在用，你可以入手看看
