### ISSUE TITLE
Y7000 2019 1050 黑果小兵 10.15.2 Clover 无法进入安装MacOS界面

### ISSUE THREAD

**Issue by iGeekl** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh_Clover#47]
您好，我的笔记本型号是Y7000 2019 1050，BIOS已经设置：  启用UEFI启动   禁用安全启动 SATA模式设置为AHCI。【黑果小兵】macOS Catalina 10.15.2 19C57 正式版 with Clover 5100原版镜像[双EFI双平台版]。但启动Clover 后，无法进入安装MacOS界面。以下是笔记本配置和报错截图，请给予解决方法，非常感谢

电脑型号	联想 81V4 笔记本电脑  
处理器	英特尔 Core i7-9750H @ 2.60GHz 六核
主板	联想 LNVNB161216 ( HM370 芯片组 )
内存	8 GB ( 海力士 DDR4 2666MHz )
主硬盘	镁光 MTFDHBA512TCK ( 512 GB / 固态硬盘 )
显卡	Nvidia GeForce GTX 1050 ( 3 GB )
显示器	友达 AUO21ED ( 15.5 英寸  )
声卡	瑞昱  @ 英特尔 High Definition Audio 控制器
网卡	英特尔 Wireless-AC 9560
![IMAG0219](https://user-images.githubusercontent.com/29330906/71337684-9e9b1e00-2587-11ea-81c2-2eeaec4fa5d2.jpg)

**Comment by iGeekl** [comment]
[https://user-images.githubusercontent.com/29330906/71337877-6fd17780-2588-11ea-90f6-567e8b0729f6.jpg](![IMAG0219]((https://user-images.githubusercontent.com/29330906/71337877-6fd17780-2588-11ea-90f6-567e8b0729f6.jpg)))

**Comment by iGeekl** [comment]
https://imgchr.com/i/lSOCbF

**Comment by xiaoMGitHub** [comment]
二、安装注意事项及常见问题 
问题一：第一次安装前期准备 
<1>、首先确定自己固态硬盘是否是三星PM981 （设备管理器查看）如果自带是三星256G及以上的SSD则无法安装(目前2019款自带的镁光固态同样无法安装，需要屏蔽)。
---------------------------------------------------------------------------------------------------------------
有时间多阅读群文件

**Comment by iGeekl** [comment]
好的 谢谢了。也就是说另外加装固态硬盘或者机械硬盘，屏蔽掉镁光固态，就可以正常安装了是吧？

**Comment by xiaoMGitHub** [comment]
是的

**Comment by iGeekl** [comment]
非常感谢您的帮助，已经成功安装，基本无大碍！感谢…
